; EJEMPLO DE CONFIGURACIÓN PARA INTERRUPCIOINES


ORG 3000H
; SUBRUTINA QUE ATIENDE A LA INTERRUPCIÒN F 10
 CONTAR:INC DL
; AVISA AL PIC QUE TERMINAMOS
 MOV AL, 20H
 OUT 20H, AL  ; EOI = 20H
 ; VOLEMOS COMN IRET
 IRET
 
ORG 2000H
; SELECCIONO EL ID 10 PARA EL F10
	MOV AX, CONTAR ; CARGO LA DIRECCIÓN DE LA SUBRUTINA
	MOV BX, 40H ;
	MOV [BX], AX ; 40 = 3000H
; HASTA ACÁ CONFIGURAMOS EL VECTOR DE INTERRUPCIONES

; AHORA CONFIGURAMOS EL PIC
CLI
; DESENMASCARAMOS LA INTERRUPCIÓN Y 
  MOV AL, 11111110B  ;HABILITO EL F10
  OUT 21H, AL ; IMR = 11111110
  
  MOV AL, 10
  OUT 24H, AL ;  INT 0 = F10 
STI
INT 0	
HLT
END