EOI  EQU 20H
IMR  EQU 21H
INT2 EQU 26H  ; DIRECCION DEL HANDSHAKE
HAND_DATO EQU 40H
HAND_ESTADO EQU 41H  ; REGISTROS DEL HANDSHAKE

ORG 1000H
 MENSAJE DB "LOS CAPITOS IMPRIMEN POR HANDSHAKE"
 FIN DB ?
 
ORG 3000H
;1) SUBRUTINA QUE ATIENDE LAS INTERRUPCIONES
	SUB_INT2: MOV AL, [BX]
			  OUT HAND_DATO, AL
			  INC BX
; LE AVISAMOS AL PIC QUE SE ATENDIO LA INTERRUPCION
			  MOV AL, 20H
			  OUT EOI, AL
	IRET
	
ORG 2000H
;2) ELEGIMOS UN ID Y GUARDAMOS LA DIRECCIONDE LA 
;   SUBRUTINA EN EL VECTOR DE INTERRUPCIONES
;------------------------------------------------------
	MOV AX, SUB_INT2 ; GUARDAMOS EN AX LA DIRECCION DE LA SUBRUTINA
	MOV BX, 40 ; 
	MOV [BX], AX ; GUARDAMOS EN LA DIRECCION 40 DEL VECTOR DE INT 3000H 
	
;3) CONFIGURAMOS EL PIC
; -----------------------------------------------------
 CLI
	MOV AL, 11111011B
	OUT IMR, AL ; ESCRIBIMOS EN EL IMR QUE SOLO HABILITAMOS EL INT2
	
	MOV AL, 10
	OUT INT2, AL ; ; AHORA BSABE QUE SU ID ES 10
 STI
;4)CONFIGURAMOS EL HANDSHAKE PARA INTERRUPCIONES
; -----------------------------------------------------
 MOV BX, OFFSET MENSAJE

	IN  AL, HAND_ESTADO
	OR  AL, 10000000B ; FORZAMOS EL BIT 7 A UNO
	OUT HAND_ESTADO, AL 
	
;5) MANDAMOS EL STRING	
 
	LOOP: CMP BX, OFFSET FIN
		  JNZ LOOP
		  
	IN  AL, HAND_ESTADO
	AND  AL, 01111111B ; FORZAMOS EL BIT 7 A CERO
	OUT HAND_ESTADO, AL 	  

INT 0
END		