ORG 1000H
	MENSAJE DB "INGRESE 3 CARACTERES"
	FIN		DB ?
	CADENA	DB ?
	
ORG 3000H 					; SUB-RUTINA PPARA IMPRIMIR MENSAJE 
PRINT_MSG: MOV BX, OFFSET MENSAJE
	MOV AL, OFFSET FIN - OFFSET MENSAJE
	INT 7
	RET
	
ORG 2000H
	CALL PRINT_MSG        ; LLAMA A SUB-RUTINA, IMPRIME MENSAJE
	MOV DL, 3             ; CANTIDAD DE CARACTERE A IMPRIMIR
	MOV BX, OFFSET CADENA ; LUGAR DONDE GUARDARA LO IMPRESO
LEER: INT 6 ; IMPRIME DE A UN CARACTER
	INC BX
	DEC DL
	JNZ LEER
	; ACA COMIENZA A IMPRIMIR	
	MOV BX, OFFSET CADENA; CADENA DESDE ESTA POSICIÒN DE MEMORIA
	MOV AL, 3     ; TANTAS VECES
	INT 7   ; INTERRUPCIÒN PARA IMPRIMIR
	INT 0
END
	